### ISSUE TITLE
Unnecessary restriction of ClientTrustStore to 7 certs in TR-03124-2_ICS_v1.2.xsd

### ISSUE THREAD

**Issue by sebastianloesch** [eID-Testbeds/client#1]
The ClientTrustStore configured in the ics.xml is limited to a maximum of 7 certificates, see [testbed/IPSmallJava/src/main/resources/TR-03124-2_ICS_v1.2.xsd](https://github.com/eID-Client-Testbed/testbed/blob/master/IPSmallJava/src/main/resources/TR-03124-2_ICS_v1.2.xsd#L63).

Currently we have the 4th generation of productive certificates and the 5th generation of test certificates, so one easily exceeds the limit of 7.

Please drop this restriction.

**Comment by sn-pos** [comment]
Ics.xml is a technical representation of the test candidate's ICS according to TR-03124 and it only contains necessary information for an appropriate test execution.
The tests definition is based on only one PKI, so seven trust points should be sufficient for quite some time.
